package com.gap.test;
/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;

import com.gap.piggyBank.PiggyBank;
import com.gap.util.Denomination;

import static org.junit.Assert.*;

public class PiggyBankTest {
	
    @Test 
    public void createPiggyBankTest() {
        PiggyBank piggyBank = new PiggyBank();
        assertNotNull(piggyBank);
    }
    
    @Test 
    public void addCoinsFiftyTest() {
    	int fiftyCoins = 3;
    	PiggyBank piggyBank = new PiggyBank();
    	piggyBank.addCoins(fiftyCoins, 0, 0, 0, 0);
        assertEquals(fiftyCoins, piggyBank.getFiftyCoins());
    }
    
    @Test 
    public void addCoinsOneHundredTest() {
    	int oneHundred = 99;
    	PiggyBank piggyBank = new PiggyBank();
    	piggyBank.addCoins(0, oneHundred, 0, 0, 0);
        assertEquals(oneHundred, piggyBank.getOneHundredCoins());
    }
    
    @Test 
    public void addCoinsTwoHundredTest() {
    	int twoHundred = 8;
    	PiggyBank piggyBank = new PiggyBank();
    	piggyBank.addCoins(0, 0, twoHundred, 0, 0);
        assertEquals(twoHundred, piggyBank.getTwoHundredCoins());
    }
    
    @Test 
    public void addCoinsFiveHundredTest() {
    	int fiveHundred = 15;
    	PiggyBank piggyBank = new PiggyBank();
    	piggyBank.addCoins(0, 0, 0, fiveHundred, 0);
        assertEquals(fiveHundred, piggyBank.getFiveHundredCoins());
    }
    
    @Test 
    public void addCoinsThousandTest() {
    	int thousand = 15;
    	PiggyBank piggyBank = new PiggyBank();
    	piggyBank.addCoins(0, 0, 0, 0, thousand);
        assertEquals(thousand, piggyBank.getThousandCoins());
    }
    
    @Test 
    public void totalCoinsTest() {
    	int thousand = 15;
    	int fifty = 32;
    	int oneHundred = 29;
    	PiggyBank piggyBank = new PiggyBank();
    	piggyBank.addCoins(fifty, oneHundred, 0, thousand, 0);
        assertEquals((thousand+fifty+oneHundred), piggyBank.totalCoins());
    }
    
    @Test 
    public void totalCoinsByFiftyTest() {
    	int fiftyCoins = 3;
    	PiggyBank piggyBank = new PiggyBank();
    	piggyBank.addCoins(fiftyCoins, 0, 0, 0, 0);
        assertEquals(fiftyCoins, piggyBank.totalCoinsByDenomination(Denomination.FIFTY));
    }
    
    @Test 
    public void totalCoinsByCoinsOneHundredTest() {
    	int oneHundred = 99;
    	PiggyBank piggyBank = new PiggyBank();
    	piggyBank.addCoins(0, oneHundred, 0, 0, 0);
    	assertEquals(oneHundred, piggyBank.totalCoinsByDenomination(Denomination.ONE_HUNDRED));
    }
    
    @Test 
    public void totalCoinsByCoinsTwoHundredTest() {
    	int twoHundred = 8;
    	PiggyBank piggyBank = new PiggyBank();
    	piggyBank.addCoins(0, 0, twoHundred, 0, 0);
    	assertEquals(twoHundred, piggyBank.totalCoinsByDenomination(Denomination.TWO_HUNDRED));
    }
    
    @Test 
    public void totalCoinsByCoinsFiveHundredTest() {
    	int fiveHundred = 15;
    	PiggyBank piggyBank = new PiggyBank();
    	piggyBank.addCoins(0, 0, 0, fiveHundred, 0);
    	assertEquals(fiveHundred, piggyBank.totalCoinsByDenomination(Denomination.FIVE_HUNDRED));
    }
    
    @Test 
    public void totalCoinsByCoinsThousandTest() {
    	int thousand = 15;
    	PiggyBank piggyBank = new PiggyBank();
    	piggyBank.addCoins(0, 0, 0, 0, thousand);
    	assertEquals(thousand, piggyBank.totalCoinsByDenomination(Denomination.THOUSAND));
    }
}
